name: Publish Package

on:
    push:
        tags:
            - v*

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/
                  cache: pnpm

            - run: pnpm install

            - name: Lint
              run: pnpm run lint

            - name: Build
              run: pnpm run build

            - name: Test
              run: pnpm run test

            - run: pnpm publish --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                  NODE_OPTIONS: --max-old-space-size=6144
